## Company Details:



== https://github.com/sunilsoni/interviews/tree/master/src/main/java/com/interview/company/airbnb/[Airbnb]
 
* https://github.com/sunilsoni/interviews/blob/master/src/main/java/com/interview/company/airbnb/AddTwoNumbers.java[*Add Two Numbers:*] 

You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order and each of their nodes contain a single digit. Add the two numbers and return it as a linked list.

Assume that:: You may assume the two numbers do not contain any leading zero, except the number 0 itself.

[source,java]
-----------------
 Input: (2 -> 4 -> 3) + (5 -> 6 -> 4)
 Output: 7 -> 0 -> 8
-----------------   

 
* https://github.com/sunilsoni/interviews/blob/master/src/main/java/com/interview/company/airbnb/ConvertSortedArrayToBinarySearchTree.java[*Convert Sorted Array To Binary Search Tree:*] 
Given an array where elements are sorted in ascending order, convert it to a height balanced BST.


* https://github.com/sunilsoni/interviews/blob/master/src/main/java/com/interview/company/airbnb/HouseRobber.java[*House Robber :*]

*1.* You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security system connected and it will automatically contact the police if two adjacent houses were broken into on the same night.

Given that:: Given a list of non-negative integers representing the amount of money of each house, determine the maximum amount of money you can rob tonight without alerting the police.
 
*2.* After robbing those houses on that street, the thief has found himself a new place for his thievery so that he will not get too much attention. This time, all houses at this place are arranged in a circle. That means the first house is the neighbor of the last one. Meanwhile, the security system for these houses remain the same as for those in the previous street.

Given that:: Given a list of non-negative integers representing the amount of money of each house, determine the maximum amount of money you can rob tonight without alerting the police.

*3.* The houses form a binary tree. If the root is robbed, its left and right can not be robbed.

* https://github.com/sunilsoni/interviews/blob/master/src/main/java/com/interview/company/airbnb/MergeKSortedLists.java[*Merge K Sorted Lists :*]
  Merge k sorted linked lists and return it as one sorted list. Analyze and describe its complexity.

* https://github.com/sunilsoni/interviews/blob/master/src/main/java/com/interview/company/airbnb/RegularExpressionMatching.java[*Regular Expression Matching:*] Implement regular expression matching with support for '.' and '*'.

'.' Matches any single character.

'*' Matches zero or more of the preceding element.

The matching should cover the entire input string (not partial).

The function prototype should be:
[source,java]
-----------------
boolean isMatch(String s, String p)
-----------------

Some examples::

[source,java]
-----------------
isMatch("aa","a") return false
isMatch("aa","aa") return true
isMatch("aaa","aa") return false
isMatch("aa", "a*") return true
isMatch("aa", ".*") return true
isMatch("ab", ".*") return true
isMatch("aab", "c*a*b") return true
-----------------


